### ISSUE TITLE
Microservices demo issue

### ISSUE THREAD

**Issue by jessberg** [dyn-tracing/microservices_env#28]
The commit https://github.com/dyn-tracing/microservices-demo/commit/3ae6891364aaf278e25c3537d50fa4ef40271a51 sends traces to the opentelemetry collector.  The current commit does not.  Where did we go wrong and how can we fix it?

**Comment by HaseebLUMS** [comment]
Resolved: https://github.com/dyn-tracing/microservices_env/commit/4417a94ba7c42728f3af663af0335c4b5e47f90f
